# Generated by Django 2.2 on 2019-04-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='teacher',
        ),
    ]
