# Generated by Django 2.2 on 2019-04-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20190413_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='images/'),
        ),
    ]
